# Advanced Physics Engines Week 1

## What is Taichi
Data-oriented, parallel, megakernels


In [1]:
!pip install taichi


  Using cached numpy-1.20.2-cp37-cp37m-win_amd64.whl (13.6 MB)
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacepy 0.2.1 requires h5py, which is not installed.
spacepy 0.2.1 requires matplotlib>=1.5, which is not installed.
spacepy 0.2.1 requires scipy>=0.10, which is not installed.


In [2]:
!pip install matplotlib


  Using cached Pillow-8.2.0-cp37-cp37m-win_amd64.whl (2.2 MB)
  Using cached kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacepy 0.2.1 requires h5py, which is not installed.
spacepy 0.2.1 requires scipy>=0.10, which is not installed.


In [3]:
!pip install h5py


  Using cached h5py-3.2.1-cp37-cp37m-win_amd64.whl (2.7 MB)
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacepy 0.2.1 requires scipy>=0.10, which is not installed.


In [5]:
!pip install scipy


In [7]:
# Getting started
import taichi as ti

ti.init(arch=ti.cuda)

[Taichi] mode=release
[Taichi] version 0.7.18, llvm 10.0.0, commit 9a31814b, win, python 3.7.10
[Taichi] Starting on arch=cuda


In [5]:
# Data
import taichi as ti
ti.init(arch=ti.cuda)

a = ti.field(dtype = ti.f32,shape = (6,4))

C = ti.Matrix.field(2,2,dtype= ti.f32,shape=(3,4))
a[1,2] = 1
print(type(a))
print(a)

[Taichi] Starting on arch=cuda
[Taichi] materializing...
<class 'taichi.lang.expr.Expr'>
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### lexically-scoped

Whats the meaning of lexically scoped?


For example, if y is referenced inside a function f, but y is not defined inside f, then y resolves to the first variable named y that is defined in the enclosing scope of the definitio of f.

In [6]:
@ti.kernel
def hello(i: ti.i32):
    a = 40
    print('Hello world!', a + i)
hello(2)

In [11]:
@ti.func 
def triple(x):
    return x *3


In [14]:
import taichi as ti

ti.init(arch = ti.cuda)
n = 320
pixels = ti.field(dtype = ti.f32,shape = (n * 2, n))

@ti.kernel
def paint(t: ti.f32):
    for i , j in pixels:
        pixels[i, j] = i * 0.001 + j* 0.002 + t
paint(0.3)
print(pixels)

[Taichi] Starting on arch=cuda
[Taichi] materializing...
[[0.3        0.30200002 0.30400002 ... 0.934      0.93600005 0.938     ]
 [0.301      0.303      0.305      ... 0.935      0.93700004 0.939     ]
 [0.30200002 0.30400002 0.30600002 ... 0.93600005 0.938      0.94000006]
 ...
 [0.93700004 0.939      0.94100004 ... 1.5710001  1.5730001  1.575     ]
 [0.938      0.94       0.94200003 ... 1.572      1.574      1.5760001 ]
 [0.93900007 0.94100004 0.9430001  ... 1.5730001  1.575      1.5770001 ]]


### Atomic Operations



### Taichi-scope

Taichi scope will be runing parallel!


In [15]:
!ti example

[Taichi] mode=release
[Taichi] version 0.7.18, llvm 10.0.0, commit 9a31814b, win, python 3.7.10

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://taichi.rtfd.io/en/stable
GitHub: https://github.com/taichi-dev/taichi
Forum:  https://forum.taichi.graphics



usage: ti example [-h] [-p] [-P] [-s]
                  {ad_gravity,autodiff_minimization,autodiff_regression,cg_possion,comet,cornell_box,euler,export_mesh,export_ply,export_videos,fem128,fem99,fractal,fullscreen,game_of_life,gui_image_io,gui_widgets,keyboard,laplace,mass_spring_3d,mass_spring_game,mciso,mciso_advanced,mgpcg,mgpcg_advanced,minimal,mnist,mnist_download_data,mpm128,mpm3d,mpm88,mpm99,mpm_lagrangian_forces,nbody_oscillator,odop_solar,particle_renderer,pbf2d,physarum,quadtree,renderer_utils,revert_image_color,sdf2d,sdf_renderer,simple_uv,stable_fluid,taichi_autodiff,taichi_bitmasked,taichi_dynamic,taichi_logo,taichi_sparse,tree_gravity,vortex_rings,waterwave}
ti example: error: the following arguments are required: name
